require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude: 
  - Guardfile

RSpec/ExampleLength:
  Max: 10
  CountAsOne: [array, heredoc, method_call, hash]

Metrics/MethodLength:
  Max: 15